//
//  main.cpp
//  2. Even Fibonacci Numbers
//
//  Created by Malika Saksena on 16/07/2016.
//  Copyright © 2016 Malika Saksena. All rights reserved.
//

/*
 
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 
 
 */


#include <iostream>
using namespace std;

int main(int argc, const char * argv[])
{
    
    //generates fibonacci sequence
    int a = 1, b = 2, term = 0;
    int max = 4e6; //the highest value of the term
    long sum = 2; //includes the first even term (as 1, 2 are not inside our loop)
    
    
    while ( term <= max)
        
    {
        
        term = a + b; //next term in the series
        
        if (term > max) //we put this condition inside the loop as well to exit if the term exceeds max, because we print it out before the next check.
        {
            break;
        }
        
        if ( term % 2 == 0 )
        {
            
            sum = sum + term;
        } //considers only the even terms
        
        a = b;
        b = term;
        
    }
    
    cout<< "Sum: " << sum;
    cout << endl;
    
    
    
    
    
    return 0;
}
